### ISSUE TITLE
This document should not present itself as a "Candidate Recommendation"

### ISSUE THREAD

**Issue by pchampin** [solid/web-access-control-spec#120] opened 2023-10-11 12:18 UTC
The term "Candidate Recommendation" is not defined, AFAICT, in the Solid Process, and is very much loaded with W3C REC-track documents. This could be perceived as a malicious attempt to give to this document a standing that it does not have.

**Comment by csarven** [comment] 2023-10-11 12:38
Right that it could be perceived that way, as with anything else. I can assure you that nothing malicious was intended for the W3C community by publishing a document under solidproject.org (you know... anyone can say anything about anything kind of applies here. :))

That said, correct that it is not defined per se besides being of course influenced by W3C's document statuses, where we use "pre-release" (based on Semantic Versioning) as described in https://github.com/solid/specification/blob/main/CONTRIBUTING.md#versioned-technical-report . (This was a Solid Editors Team decision part of the Solid Process in the past but it is no longer applicable in the CG given its own charter: https://www.w3.org/community/solid/charter/ ).

So, happy to follow up and use different codes for pre-release (or no pre-release) and no significant well-known W3C document statuses to not further confuse anyone. You'll see the changes in CONTRIBUTING and in [WAC ED](https://solid.github.io/web-access-control-spec/) soon..

Thanks.

**Comment by koalie** [comment] 2023-10-11 15:36
> I can assure you that nothing malicious was intended

I am not aware that there is suspicion.
Thanks @csarven

**Comment by csarven** [comment] 2023-11-06 11:05
Just FYI that I've updated the pre-release example in https://github.com/solid/specification/blob/main/CONTRIBUTING.md#versioned-technical-report from "WD" to "CG-DRAFT". Let me know if that suffices for you and that we can close this issue.

Moreover, https://solidproject.org/TR/2022/wac-20220705 is the only versioned specification that's marked as a CR. As mentioned/agreed, future Solid specifications will not use terminology from the W3C Recommendation track.

Note also that the editor's draft of the specification is only marked as ED: https://solid.github.io/web-access-control-spec/ . When a new snapshot of that specification is made, it'll be a CG-DRAFT (or off chance CG-FINAL).

On a related note to ED, please note this issue as it requests for clarification on W3C Process whether CGs can have an "ED" even: https://github.com/w3c/tr-pages/issues/102

**Comment by pchampin** [comment] 2023-11-09 09:02
Thanks a lot for these changes. I'm ok with closing this issue.

**Closed** 2023-11-27 15:51 UTC
Labels: status: Commenter Satisfied
